Implement redux
Oniocha/Qargo-Ecommerce pull request #11
Opened 2023-09-22 15:49 UTC by Haywayaheadshot

## What?
   - I implemented redux in the project. I refactored the code to improve optimization and do away with the API folder, and API calls in components.

## Why?

   - To ensure the application has a single source of truth.

## How?
   - I added redux toolkit for state management
   - I converted API calls to thunks in slices
   - I received all queries in NewArrivals.js through the redux store to ensure a single source of truth
   - I deleted the initial API calls in NewArrivals.js
   - I created store to load filter categories
   - I created actions and reducers for filtering products on display.
   - I created actions and reducers to read an individual products and list related items to that product.

2023-10-05 15:52 UTC, DavidQuartz commented
Let's Implement the vendor APIs after this PR has been reviewed and merged. The commits are pretty long now @Haywayaheadshot

2023-10-11 14:48 UTC, DavidQuartz commented
> @DavidQuartz I have implemented all but the axios request.use and request.set configurations. I am still a bit confused as to how to do that so I am reading more on it. Can I create a separate issue for that for feature reference?

Yes defintely. I will review this PR and merge if everything looks good. Thank you @Haywayaheadshot

2023-10-11 14:53 UTC, Haywayaheadshot commented
@DavidQuartz You're welcome. I just realised I still have to implement the vendor API. Working on it now

2023-10-14 17:09 UTC, Haywayaheadshot commented
@DavidQuartz Please commence the review

2023-10-15 21:49 UTC, DavidQuartz requested changes
Good work @Haywayaheadshot. Kindly checkout the comments I added.

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/vendor/action.js
> +        rejectWithValue(error);
you should always return the `rejectWithValue` otherwise nothing gets returned

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/api.js
> +export const baseUrl = axiosInstance;
`baseUrl` is not a descriptive name for the axios instance. `axiosInstance` is much better.

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/api.js
> +const axiosInstance = axios.create({
You can export this `const` as a named export at the end of the file, instead of reassigning it to another variable and export that

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/departments/Departments.js
> +            state.departmentsApiError = action.payload;
What is the structure of the error? We only need the error message, and not the entire error object

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/orders/Orders.js
> +            state.guestDataError = action.payload;
We only need the relevant field out of the entire error payload

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/orders/Orders.js
> +            state.loading = true;
In pending, we should set error and success states also to their default states

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/orders/Orders.js
> +        builder.addCase(createAuthOrder.pending, (state) => {
In pending, we should set error and success states also to their default states. Please make this change in all other reducers necessary

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/orders/Orders.js
> +        builder.addCase(createAuthOrder.fulfilled, (state, action) => {
In fulfilled, we should set error state to their default state. Please make this change in all other reducers necessary

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/orders/Orders.js
> +        builder.addCase(createGuestOrder.fulfilled, (state, action) => {
In fulfilled, we should set error state to their default state

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/product/filteredProducts/actions.js
> +    const query = {
Is params always supplied to this action?
I see nothing passed [here](https://github.com/Oniocha/Qargo-Ecommerce/pull/11/files#diff-d70b1568fcc78bad0e342846f883db2a81f86af4529b3997a34968452c299d37R26)

In that case the params would be undefined and the request will be made with it. Only construct the query object if params is present.

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/product/loadProducts/actions.js
> +       const getProductsByPriceApi = `${productsEndPointApi}?sortBy=price&order=asc&limit=10`;
We should avoid hardcoding moving forward. We can have these as default values for the thunk's parameters rather than hard coding.

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/product/loadProducts/actions.js
> +        rejectWithValue(error)
You forgot the return keyword. Please make this change wherever necessary

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/redux/product/loadProducts/actions.js
> +        const getNewArrivalsApi = `${productsEndPointApi}?sortBy=sold&order=desc&limit=10`;
We should avoid hardcoding moving forward. We can have these as default values for the thunk's parameters rather than hard coding.

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/Pages/CheckoutPage/CheckOutPage.jsx
> +    dispatch(getTransactionFees({cost: 14}))
Why do we have 14 hardcoded?

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/Pages/Shop/Shop.jsx
> +    dispatch(getFilteredProducts(skip, limit, newFilters))
Did you test this? Passing 3 parameters to the action? The `options` parameter is only the first one

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/Pages/Shop/Shop.jsx
> +    dispatch(updateFilteredProducts(toSkip, limit, filter))
Did you test this? Passing 3 parameters to the action? The `options` parameter is only the first one

2023-10-15 21:49 UTC, DavidQuartz commented on Qfront/src/Pages/Shop/Shop.jsx
>      loadFilteredResults(limit, skip, myFilters.filters);
Did you test this? Passing 3 parameters to the action? The `options` parameter is only the first one

2023-10-19 14:17 UTC, Haywayaheadshot commented
@DavidQuartz I have made the corrections we spoke about yesterday

2023-10-19 14:51 UTC, DavidQuartz requested changes

2023-10-19 14:51 UTC, DavidQuartz commented on Qfront/src/Pages/Admin/AddCategory.jsx
> +    dispatch(createCategory(user._id, access, { name }))
this thunk is receiving it's parameters wrongly. Please check to make sure all the thunks are receiving parameters as one argument (could be an object), not as multiple arguments

2023-10-28 19:05 UTC, merged